var MONTH_NAMES = {
  2: "February", 3: "March", 4: "April", 5: "May",
  6: "June", 7: "July", 8: "August", 9: "September"
};

var MONTH_COLORS = {
  2: "#a78bfa", 3: "#34d399", 4: "#60a5fa", 5: "#f472b6",
  6: "#fb923c", 7: "#facc15", 8: "#f87171", 9: "#c8a96e"
};

var PHOTOS = [
  {file:"images/Feb 14-1.jpeg",month:2,day:14,label:"Feb 14",lat:null,lng:null,state:""},
  {file:"images/Feb 21-2.jpeg",month:2,day:21,label:"Feb 21",lat:null,lng:null,state:""},
  {file:"images/Mar 1-1.jpeg",month:3,day:1,label:"Mar 1",lat:null,lng:null,state:""},
  {file:"images/Mar 2-1.jpeg",month:3,day:2,label:"Mar 2",lat:null,lng:null,state:""},
  {file:"images/Mar 3-1.jpeg",month:3,day:3,label:"Mar 3",lat:null,lng:null,state:""},
  {file:"images/Mar 4-1.jpeg",month:3,day:4,label:"Mar 4",lat:null,lng:null,state:""},
  {file:"images/Mar 5-1.jpeg",month:3,day:5,label:"Mar 5",lat:null,lng:null,state:""},
  {file:"images/Mar 6-1.jpeg",month:3,day:6,label:"Mar 6",lat:null,lng:null,state:""},
  {file:"images/Mar 7-1.jpeg",month:3,day:7,label:"Mar 7",lat:null,lng:null,state:""},
  {file:"images/Mar 8-1.jpeg",month:3,day:8,label:"Mar 8",lat:null,lng:null,state:""},
  {file:"images/Mar 9-1.jpeg",month:3,day:9,label:"Mar 9",lat:null,lng:null,state:""},
  {file:"images/Mar 10-1.jpeg",month:3,day:10,label:"Mar 10",lat:null,lng:null,state:""},
  {file:"images/Mar 11-1.jpeg",month:3,day:11,label:"Mar 11",lat:null,lng:null,state:""},
  {file:"images/Mar 12-1.jpeg",month:3,day:12,label:"Mar 12",lat:null,lng:null,state:""},
  {file:"images/Mar 13-1.jpeg",month:3,day:13,label:"Mar 13",lat:null,lng:null,state:""},
  {file:"images/Mar 14-1.jpeg",month:3,day:14,label:"Mar 14",lat:null,lng:null,state:""},
  {file:"images/Mar 15-1.jpeg",month:3,day:15,label:"Mar 15",lat:null,lng:null,state:""},
  {file:"images/Mar 16-1.jpeg",month:3,day:16,label:"Mar 16",lat:null,lng:null,state:""},
  {file:"images/Mar 17-1.jpeg",month:3,day:17,label:"Mar 17",lat:null,lng:null,state:""},
  {file:"images/Mar 18-1.jpeg",month:3,day:18,label:"Mar 18",lat:null,lng:null,state:""},
  {file:"images/Mar 19-1.jpeg",month:3,day:19,label:"Mar 19",lat:null,lng:null,state:""},
  {file:"images/Mar 20-1.jpeg",month:3,day:20,label:"Mar 20",lat:null,lng:null,state:""},
  {file:"images/Mar 21-1.jpeg",month:3,day:21,label:"Mar 21",lat:null,lng:null,state:""},
  {file:"images/Mar 22-1.jpeg",month:3,day:22,label:"Mar 22",lat:null,lng:null,state:""},
  {file:"images/Mar 23-1.jpeg",month:3,day:23,label:"Mar 23",lat:null,lng:null,state:""},
  {file:"images/Mar 24-1.jpeg",month:3,day:24,label:"Mar 24",lat:null,lng:null,state:""},
  {file:"images/Mar 25-1.jpeg",month:3,day:25,label:"Mar 25",lat:null,lng:null,state:""},
  {file:"images/Mar 26-1.jpeg",month:3,day:26,label:"Mar 26",lat:null,lng:null,state:""},
  {file:"images/Mar 27-1.jpeg",month:3,day:27,label:"Mar 27",lat:null,lng:null,state:""},
  {file:"images/Mar 28-1.jpeg",month:3,day:28,label:"Mar 28",lat:null,lng:null,state:""},
  {file:"images/Mar 29-1.jpeg",month:3,day:29,label:"Mar 29",lat:null,lng:null,state:""},
  {file:"images/Mar 30-1.jpeg",month:3,day:30,label:"Mar 30",lat:null,lng:null,state:""},
  {file:"images/Apr 1-1.jpeg",month:4,day:1,label:"Apr 1",lat:null,lng:null,state:""},
  {file:"images/Apr 2-1.jpeg",month:4,day:2,label:"Apr 2",lat:null,lng:null,state:""},
  {file:"images/Apr 3-1.jpeg",month:4,day:3,label:"Apr 3",lat:null,lng:null,state:""},
  {file:"images/Apr 5-1.jpeg",month:4,day:5,label:"Apr 5",lat:null,lng:null,state:""},
  {file:"images/Apr 8-1.jpeg",month:4,day:8,label:"Apr 8",lat:null,lng:null,state:""},
  {file:"images/Apr 10-1.jpeg",month:4,day:10,label:"Apr 10",lat:null,lng:null,state:""},
  {file:"images/Apr 12-1.jpeg",month:4,day:12,label:"Apr 12",lat:null,lng:null,state:""},
  {file:"images/Apr 15-1.jpeg",month:4,day:15,label:"Apr 15",lat:null,lng:null,state:""},
  {file:"images/Apr 18-1.jpeg",month:4,day:18,label:"Apr 18",lat:null,lng:null,state:""},
  {file:"images/Apr 20-1.jpeg",month:4,day:20,label:"Apr 20",lat:null,lng:null,state:""},
  {file:"images/Apr 22-1.jpeg",month:4,day:22,label:"Apr 22",lat:null,lng:null,state:""},
  {file:"images/Apr 25-1.jpeg",month:4,day:25,label:"Apr 25",lat:null,lng:null,state:""},
  {file:"images/Apr 28-1.jpeg",month:4,day:28,label:"Apr 28",lat:null,lng:null,state:""},
  {file:"images/May 1-1.jpeg",month:5,day:1,label:"May 1",lat:null,lng:null,state:""},
  {file:"images/May 4-1.jpeg",month:5,day:4,label:"May 4",lat:null,lng:null,state:""},
  {file:"images/May 7-1.jpeg",month:5,day:7,label:"May 7",lat:null,lng:null,state:""},
  {file:"images/May 10-1.jpeg",month:5,day:10,label:"May 10",lat:null,lng:null,state:""},
  {file:"images/May 13-1.jpeg",month:5,day:13,label:"May 13",lat:null,lng:null,state:""},
  {file:"images/May 16-1.jpeg",month:5,day:16,label:"May 16",lat:null,lng:null,state:""},
  {file:"images/May 19-1.jpeg",month:5,day:19,label:"May 19",lat:null,lng:null,state:""},
  {file:"images/May 22-1.jpeg",month:5,day:22,label:"May 22",lat:null,lng:null,state:""},
  {file:"images/May 25-1.jpeg",month:5,day:25,label:"May 25",lat:null,lng:null,state:""},
  {file:"images/May 28-1.jpeg",month:5,day:28,label:"May 28",lat:null,lng:null,state:""},
  {file:"images/Jun 1-1.jpeg",month:6,day:1,label:"Jun 1",lat:null,lng:null,state:""},
  {file:"images/Jun 4-1.jpeg",month:6,day:4,label:"Jun 4",lat:null,lng:null,state:""},
  {file:"images/Jun 8-1.jpeg",month:6,day:8,label:"Jun 8",lat:null,lng:null,state:""},
  {file:"images/Jun 12-1.jpeg",month:6,day:12,label:"Jun 12",lat:null,lng:null,state:""},
  {file:"images/Jun 16-1.jpeg",month:6,day:16,label:"Jun 16",lat:null,lng:null,state:""},
  {file:"images/Jun 20-1.jpeg",month:6,day:20,label:"Jun 20",lat:null,lng:null,state:""},
  {file:"images/Jun 24-1.jpeg",month:6,day:24,label:"Jun 24",lat:null,lng:null,state:""},
  {file:"images/Jul 1-1.jpeg",month:7,day:1,label:"Jul 1",lat:null,lng:null,state:""},
  {file:"images/Jul 4-1.jpeg",month:7,day:4,label:"Jul 4",lat:null,lng:null,state:""},
  {file:"images/Jul 8-1.jpeg",month:7,day:8,label:"Jul 8",lat:null,lng:null,state:""},
  {file:"images/Jul 12-1.jpeg",month:7,day:12,label:"Jul 12",lat:null,lng:null,state:""},
  {file:"images/Jul 16-1.jpeg",month:7,day:16,label:"Jul 16",lat:null,lng:null,state:""},
  {file:"images/Jul 20-1.jpeg",month:7,day:20,label:"Jul 20",lat:null,lng:null,state:""},
  {file:"images/Jul 24-1.jpeg",month:7,day:24,label:"Jul 24",lat:null,lng:null,state:""},
  {file:"images/Jul 28-1.jpeg",month:7,day:28,label:"Jul 28",lat:null,lng:null,state:""},
  {file:"images/Aug 30-4.jpeg",month:8,day:30,label:"Aug 30",lat:null,lng:null,state:""},
  {file:"images/Aug 30-5.jpeg",month:8,day:30,label:"Aug 30",lat:null,lng:null,state:""},
  {file:"images/Aug 31-1.jpeg",month:8,day:31,label:"Aug 31",lat:null,lng:null,state:""},
  {file:"images/Aug 31-4.jpeg",month:8,day:31,label:"Aug 31",lat:null,lng:null,state:""},
  {file:"images/Aug 31-5.jpeg",month:8,day:31,label:"Aug 31",lat:null,lng:null,state:""},
  {file:"images/Aug 31-6.jpeg",month:8,day:31,label:"Aug 31",lat:null,lng:null,state:""},
  {file:"images/Aug 31-7.jpeg",month:8,day:31,label:"Aug 31",lat:null,lng:null,state:""},
  {file:"images/Aug 31-8.jpeg",month:8,day:31,label:"Aug 31",lat:null,lng:null,state:""},
  {file:"images/Sept 4-1.jpeg",month:9,day:4,label:"Sep 4",lat:null,lng:null,state:""},
  {file:"images/Sept 4-2.jpeg",month:9,day:4,label:"Sep 4",lat:null,lng:null,state:""},
  {file:"images/Sept 6-1.jpeg",month:9,day:6,label:"Sep 6",lat:null,lng:null,state:""},
  {file:"images/Sept 6-2.jpeg",month:9,day:6,label:"Sep 6",lat:null,lng:null,state:""},
  {file:"images/Sept 7-1.jpeg",month:9,day:7,label:"Sep 7",lat:null,lng:null,state:""},
  {file:"images/Sept 8-1.jpeg",month:9,day:8,label:"Sep 8",lat:null,lng:null,state:""},
  {file:"images/Sept 11-1.jpeg",month:9,day:11,label:"Sep 11",lat:null,lng:null,state:""},
  {file:"images/Sept 15-1.PNG",month:9,day:15,label:"Sep 15",lat:null,lng:null,state:""},
  {file:"images/Sept 17-1.jpeg",month:9,day:17,label:"Sep 17",lat:null,lng:null,state:""},
  {file:"images/Sept 17-2.jpeg",month:9,day:17,label:"Sep 17",lat:null,lng:null,state:""},
  {file:"images/sept 19-1.jpeg",month:9,day:19,label:"Sep 19",lat:null,lng:null,state:""}
];
