// Auto-generated by generate_photos_js.py
// Generated: 2026-03-18 13:02:15
// Total photos: 726
// With GPS data: 325
// Without GPS: 401

const photoLocations = [
  { filename: '2.February\\Photos\\Feb 15.jpeg', lat: 32.632722, lng: -96.816856, date: '2022:02:15 13:30:25' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2019.jpeg', lat: 32.632678, lng: -96.817131, date: '2022:02:17 22:06:18' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2020.jpeg', lat: 32.632692, lng: -96.817086, date: '2022:02:17 22:09:50' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2021.jpeg', lat: 32.632692, lng: -96.817086, date: '2022:02:17 22:09:57' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2022.jpeg', lat: 32.632675, lng: -96.817108, date: '2022:02:17 22:10:18' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2023.jpeg', lat: 32.632683, lng: -96.8171, date: '2022:02:17 22:10:24' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2024.jpeg', lat: 32.632683, lng: -96.817108, date: '2022:02:17 22:10:32' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2025.jpeg', lat: 32.632683, lng: -96.817108, date: '2022:02:17 22:10:40' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2026.jpeg', lat: 32.632678, lng: -96.8171, date: '2022:02:17 22:10:54' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2027.jpeg', lat: 32.632678, lng: -96.817117, date: '2022:02:17 22:11:00' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2028.jpeg', lat: 32.632672, lng: -96.817117, date: '2022:02:17 22:11:09' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2029.jpeg', lat: 32.632678, lng: -96.8171, date: '2022:02:17 22:11:16' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2030.jpeg', lat: 32.632678, lng: -96.817108, date: '2022:02:17 22:11:32' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2031.jpeg', lat: 32.632672, lng: -96.817108, date: '2022:02:17 22:11:36' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2032.jpeg', lat: 32.632672, lng: -96.817108, date: '2022:02:17 22:11:45' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2033.jpeg', lat: 32.632664, lng: -96.817122, date: '2022:02:17 22:11:49' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2034.jpeg', lat: 32.632667, lng: -96.817122, date: '2022:02:17 22:12:01' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2035.jpeg', lat: 32.632672, lng: -96.817117, date: '2022:02:17 22:12:05' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2036.jpeg', lat: 32.632672, lng: -96.817108, date: '2022:02:17 22:12:15' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2037.jpeg', lat: 32.632675, lng: -96.817117, date: '2022:02:17 22:12:21' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2038.jpeg', lat: 32.632672, lng: -96.817117, date: '2022:02:17 22:12:40' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2039.jpeg', lat: 32.632653, lng: -96.817122, date: '2022:02:17 22:12:45' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2040.jpeg', lat: 32.632667, lng: -96.817117, date: '2022:02:17 22:12:58' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2041.jpeg', lat: 32.632675, lng: -96.817117, date: '2022:02:17 22:13:04' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2042.jpeg', lat: 32.632672, lng: -96.8171, date: '2022:02:17 22:13:17' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2043.jpeg', lat: 32.632672, lng: -96.8171, date: '2022:02:17 22:13:22' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2044.jpeg', lat: 32.632683, lng: -96.817122, date: '2022:02:17 22:13:35' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2045.jpeg', lat: 32.632683, lng: -96.817122, date: '2022:02:17 22:13:40' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2046.jpeg', lat: 32.632678, lng: -96.817122, date: '2022:02:17 22:13:49' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2047.jpeg', lat: 32.632667, lng: -96.817117, date: '2022:02:17 22:13:52' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2048.jpeg', lat: 32.632672, lng: -96.817108, date: '2022:02:17 22:13:59' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2049.jpeg', lat: 32.632667, lng: -96.817117, date: '2022:02:17 22:14:05' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2050.jpeg', lat: 32.632664, lng: -96.817108, date: '2022:02:17 22:14:15' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2051.jpeg', lat: 32.632647, lng: -96.817108, date: '2022:02:17 22:14:21' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2052.jpeg', lat: 32.632656, lng: -96.817122, date: '2022:02:17 22:14:26' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2053.jpeg', lat: 32.632656, lng: -96.817122, date: '2022:02:17 22:14:30' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2054.jpeg', lat: 32.632661, lng: -96.817108, date: '2022:02:17 22:14:44' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2055.jpeg', lat: 32.632661, lng: -96.817108, date: '2022:02:17 22:14:48' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2056.jpeg', lat: 32.632656, lng: -96.817122, date: '2022:02:17 22:14:57' },
  { filename: '2.February\\Photos\\Feb 17 Study Sheets\\IMG_2057.jpeg', lat: 32.632661, lng: -96.817131, date: '2022:02:17 22:15:01' },
  { filename: '2.February\\Photos\\Feb 17.jpeg', lat: 32.632664, lng: -96.8171, date: '2022:02:17 16:18:02' },
  { filename: '2.February\\Photos\\Feb 21-1.jpeg', lat: 32.632664, lng: -96.8171, date: '2022:02:21 07:20:16' },
  { filename: '2.February\\Photos\\Feb 21-2.jpeg', lat: 32.632644, lng: -96.817131, date: '2022:02:21 18:08:07' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2074.jpeg', lat: 32.632672, lng: -96.817108, date: '2022:02:28 17:09:07' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2085.jpeg', lat: 32.632642, lng: -96.817139, date: '2022:02:28 17:12:23' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2086.jpeg', lat: 32.632642, lng: -96.817131, date: '2022:02:28 17:12:39' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2087.jpeg', lat: 32.632661, lng: -96.817122, date: '2022:02:28 17:12:49' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2088.jpeg', lat: 32.632653, lng: -96.817122, date: '2022:02:28 17:12:56' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2089.jpeg', lat: 32.632656, lng: -96.817117, date: '2022:02:28 17:13:17' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2090.jpeg', lat: 32.632653, lng: -96.817131, date: '2022:02:28 17:13:26' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2091.jpeg', lat: 32.632653, lng: -96.817147, date: '2022:02:28 17:13:33' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2092.jpeg', lat: 32.632644, lng: -96.817147, date: '2022:02:28 17:13:40' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2093.jpeg', lat: 32.632647, lng: -96.817153, date: '2022:02:28 17:13:58' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2094.jpeg', lat: 32.632653, lng: -96.817161, date: '2022:02:28 17:14:06' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2095.jpeg', lat: 32.632667, lng: -96.817153, date: '2022:02:28 17:14:14' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2096.jpeg', lat: 32.632664, lng: -96.817139, date: '2022:02:28 17:14:21' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2097.jpeg', lat: 32.632656, lng: -96.817139, date: '2022:02:28 17:14:36' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2098.jpeg', lat: 32.632656, lng: -96.817147, date: '2022:02:28 17:14:40' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2099.jpeg', lat: 32.632653, lng: -96.817147, date: '2022:02:28 17:14:48' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2100.jpeg', lat: 32.632664, lng: -96.817131, date: '2022:02:28 17:14:56' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2101.jpeg', lat: 32.632664, lng: -96.817122, date: '2022:02:28 17:15:07' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2102.jpeg', lat: 32.632664, lng: -96.817139, date: '2022:02:28 17:15:12' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2103.jpeg', lat: 32.632653, lng: -96.817147, date: '2022:02:28 17:15:20' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2104.jpeg', lat: 32.632653, lng: -96.817147, date: '2022:02:28 17:15:31' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2105.jpeg', lat: 32.632672, lng: -96.817139, date: '2022:02:28 17:15:48' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2106.jpeg', lat: 32.632667, lng: -96.817139, date: '2022:02:28 17:15:52' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2107.jpeg', lat: 32.632653, lng: -96.817139, date: '2022:02:28 17:16:01' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2108.jpeg', lat: 32.632656, lng: -96.817147, date: '2022:02:28 17:16:06' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2109.jpeg', lat: 32.632683, lng: -96.817139, date: '2022:02:28 17:16:35' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2110.jpeg', lat: 32.632683, lng: -96.817139, date: '2022:02:28 17:16:40' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2111.jpeg', lat: 32.632661, lng: -96.817153, date: '2022:02:28 17:16:56' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2112.jpeg', lat: 32.632661, lng: -96.817161, date: '2022:02:28 17:17:01' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2113.jpeg', lat: 32.632667, lng: -96.817153, date: '2022:02:28 17:17:12' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2114.jpeg', lat: 32.632667, lng: -96.817153, date: '2022:02:28 17:17:16' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2115.jpeg', lat: 32.632683, lng: -96.817139, date: '2022:02:28 17:17:25' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2116.jpeg', lat: 32.632672, lng: -96.817147, date: '2022:02:28 17:17:29' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2117.jpeg', lat: 32.632672, lng: -96.817147, date: '2022:02:28 17:17:42' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2118.jpeg', lat: 32.632672, lng: -96.817131, date: '2022:02:28 17:17:49' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2119.jpeg', lat: 32.632661, lng: -96.817139, date: '2022:02:28 17:18:05' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2120.jpeg', lat: 32.632661, lng: -96.817139, date: '2022:02:28 17:18:10' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2121.jpeg', lat: 32.632672, lng: -96.817131, date: '2022:02:28 17:18:24' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2122.jpeg', lat: 32.632667, lng: -96.817161, date: '2022:02:28 17:18:37' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2123.jpeg', lat: 32.632656, lng: -96.817161, date: '2022:02:28 17:18:47' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2124.jpeg', lat: 32.632664, lng: -96.817169, date: '2022:02:28 17:18:52' },
  { filename: '2.February\\Photos\\Feb 28 Study Material\\IMG_2125.jpeg', lat: 32.632672, lng: -96.817153, date: '2022:02:28 17:19:00' },
  { filename: '3.March\\Photos\\March 5\\IMG_2133.jpeg', lat: 30.167003, lng: -95.426772, date: '2022:03:05 09:05:16' },
  { filename: '3.March\\Photos\\March 5\\IMG_2134.jpeg', lat: 30.167003, lng: -95.426772, date: '2022:03:05 09:05:24' },
  { filename: '3.March\\Photos\\March 5\\IMG_2135.jpeg', lat: 30.167003, lng: -95.426772, date: '2022:03:05 09:05:32' },
  { filename: '3.March\\Photos\\March 5\\IMG_2136.jpeg', lat: 30.167003, lng: -95.426772, date: '2022:03:05 09:05:40' },
  { filename: '3.March\\Photos\\March 8-1.jpeg', lat: 32.632661, lng: -96.817131, date: '2022:03:08 07:04:30' },
  { filename: '3.March\\Photos\\March 8-2.jpeg', lat: 32.632675, lng: -96.817139, date: '2022:03:08 07:04:54' },
  { filename: '3.March\\Photos\\March 9.jpeg', lat: 32.632692, lng: -96.817161, date: '2022:03:09 16:30:08' },
  { filename: '3.March\\Photos\\March 10-1.jpeg', lat: 32.632733, lng: -96.816864, date: '2022:03:10 11:22:38' },
  { filename: '3.March\\Photos\\March 10-2.jpeg', lat: 32.632714, lng: -96.816842, date: '2022:03:10 11:46:50' },
  { filename: '3.March\\Photos\\March 10-3.jpeg', lat: 32.6325, lng: -96.817183, date: '2022:03:10 14:15:34' },
  { filename: '3.March\\Photos\\March 10-4.jpeg', lat: 32.632625, lng: -96.817183, date: '2022:03:10 14:19:29' },
  { filename: '3.March\\Photos\\March 10-5.jpeg', lat: 32.632667, lng: -96.817092, date: '2022:03:10 14:20:16' },
  { filename: '3.March\\Photos\\March 12-1.jpeg', lat: 30.166936, lng: -95.426606, date: '2022:03:12 14:02:58' },
  { filename: '3.March\\Photos\\March 12-2.jpeg', lat: 32.631069, lng: -96.815522, date: '2022:03:12 22:17:04' },
  { filename: '3.March\\Photos\\March 14-1.jpeg', lat: 40.04485, lng: -95.13935, date: '2022:03:14 09:54:22' },
  { filename: '3.March\\Photos\\March 14-3.jpeg', lat: 40.806058, lng: -96.750297, date: '2022:03:14 11:46:25' },
  { filename: '3.March\\Photos\\March 14-4.jpeg', lat: 40.767672, lng: -98.571931, date: '2022:03:14 15:09:17' },
  { filename: '3.March\\Photos\\March 14-5.jpeg', lat: 40.767222, lng: -98.573464, date: '2022:03:14 15:09:21' },
  { filename: '3.March\\Photos\\March 14-6.jpeg', lat: 40.766694, lng: -98.575286, date: '2022:03:14 15:09:27' },
  { filename: '3.March\\Photos\\March 14-7.jpeg', lat: 40.766606, lng: -98.575592, date: '2022:03:14 15:09:29' },
  { filename: '3.March\\Photos\\March 14-9.jpeg', lat: 41.113644, lng: -101.712447, date: '2022:03:14 18:21:35' },
  { filename: '3.March\\Photos\\March 14-10.jpeg', lat: 41.328553, lng: -105.619706, date: '2022:03:14 21:54:24' },
  { filename: '3.March\\Photos\\March 14-11.jpeg', lat: 41.328531, lng: -105.619744, date: '2022:03:14 22:31:57' },
  { filename: '3.March\\Photos\\March 15-2.jpeg', lat: 41.686492, lng: -108.811669, date: '2022:03:15 08:26:50' },
  { filename: '3.March\\Photos\\March 15-3.jpeg', lat: 41.601189, lng: -109.152564, date: '2022:03:15 08:45:00' },
  { filename: '3.March\\Photos\\March 15-4.jpeg', lat: 41.534333, lng: -109.368942, date: '2022:03:15 09:16:07' },
  { filename: '3.March\\Photos\\March 15-6.jpeg', lat: 41.297531, lng: -110.557075, date: '2022:03:15 11:15:52' },
  { filename: '3.March\\Photos\\March 15-7.jpeg', lat: 41.297467, lng: -110.558997, date: '2022:03:15 11:15:58' },
  { filename: '3.March\\Photos\\March 15-8.jpeg', lat: 40.989722, lng: -111.405953, date: '2022:03:15 13:32:44' },
  { filename: '3.March\\Photos\\March 15-9.jpeg', lat: 40.989722, lng: -111.405953, date: '2022:03:15 13:32:48' },
  { filename: '3.March\\Photos\\March 15-10.jpeg', lat: 40.989967, lng: -111.406264, date: '2022:03:15 13:33:35' },
  { filename: '3.March\\Photos\\March 16-1.jpeg', lat: 45.3509, lng: -118.1979, date: '2022:03:16 06:57:36' },
  { filename: '3.March\\Photos\\March 16-2.jpeg', lat: 45.343078, lng: -118.234764, date: '2022:03:16 06:59:52' },
  { filename: '3.March\\Photos\\March 16-3.jpeg', lat: 45.583181, lng: -118.591308, date: '2022:03:16 07:30:04' },
  { filename: '3.March\\Photos\\March 16-4.jpeg', lat: 45.832767, lng: -119.767897, date: '2022:03:16 08:42:58' },
  { filename: '3.March\\Photos\\March 16-5.jpeg', lat: 45.832806, lng: -119.768281, date: '2022:03:16 08:51:50' },
  { filename: '3.March\\Photos\\March 16-6.jpeg', lat: 45.79765, lng: -120.01545, date: '2022:03:16 09:03:38' },
  { filename: '3.March\\Photos\\March 16-7.jpeg', lat: 45.691742, lng: -120.417839, date: '2022:03:16 09:23:22' },
  { filename: '3.March\\Photos\\March 16-8.jpeg', lat: 45.632653, lng: -121.212053, date: '2022:03:16 10:05:42' },
  { filename: '3.March\\Photos\\March 16-9.jpeg', lat: 45.633611, lng: -121.211739, date: '2022:03:16 10:05:46' },
  { filename: '3.March\\Photos\\March 16-10.jpeg', lat: 45.704278, lng: -121.608681, date: '2022:03:16 10:27:09' },
  { filename: '3.March\\Photos\\March 16-11.jpeg', lat: 45.704556, lng: -121.610717, date: '2022:03:16 10:27:14' },
  { filename: '3.March\\Photos\\March 16-12.jpeg', lat: 45.704544, lng: -121.616539, date: '2022:03:16 10:27:30' },
  { filename: '3.March\\Photos\\March 16-13.jpeg', lat: 45.703861, lng: -121.620033, date: '2022:03:16 10:27:40' },
  { filename: '3.March\\Photos\\March 16-14.jpeg', lat: 45.687553, lng: -121.70305, date: '2022:03:16 10:33:51' },
  { filename: '3.March\\Photos\\March 16-15.jpeg', lat: 45.690617, lng: -121.729492, date: '2022:03:16 10:34:09' },
  { filename: '3.March\\Photos\\March 16-16.jpeg', lat: 45.690647, lng: -121.730461, date: '2022:03:16 10:34:11' },
  { filename: '3.March\\Photos\\March 17-2.jpeg', lat: 47.602203, lng: -122.325281, date: '2022:03:17 08:56:26' },
  { filename: '3.March\\Photos\\March 17-3.jpeg', lat: 47.60545, lng: -122.328308, date: '2022:03:17 08:57:47' },
  { filename: '3.March\\Photos\\March 17-4.jpeg', lat: 48.000294, lng: -122.173942, date: '2022:03:17 09:35:22' },
  { filename: '3.March\\Photos\\March 17-5.jpeg', lat: 48.001136, lng: -122.173828, date: '2022:03:17 09:35:25' },
  { filename: '3.March\\Photos\\March 18.jpeg', lat: 46.802581, lng: -123.011497, date: '2022:03:18 08:19:53' },
  { filename: '3.March\\Photos\\March 19-1.jpeg', lat: 44.7813, lng: -117.813469, date: '2022:03:19 19:15:36' },
  { filename: '3.March\\Photos\\March 19-2.jpeg', lat: 44.781711, lng: -117.813225, date: '2022:03:19 20:35:17' },
  { filename: '3.March\\Photos\\March 23.jpeg', lat: 41.127042, lng: -111.769311, date: '2022:03:23 15:25:48' },
  { filename: '3.March\\Photos\\March 24.jpeg', lat: 47.436169, lng: -122.223725, date: '2022:03:24 12:13:41' },
  { filename: '3.March\\Photos\\March 25-1.jpeg', lat: 45.536939, lng: -122.481567, date: '2022:03:25 10:26:03' },
  { filename: '3.March\\Photos\\March 25-2.jpg', lat: 45.536772, lng: -122.477736, date: '' },
  { filename: '3.March\\Photos\\March 25-3.jpeg', lat: 45.543786, lng: -122.394928, date: '2022:03:25 21:01:21' },
  { filename: '3.March\\Photos\\March 26.jpeg', lat: 42.393519, lng: -113.294419, date: '2022:03:26 19:04:28' },
  { filename: '3.March\\Photos\\March 27-2.jpeg', lat: 40.363083, lng: -104.984031, date: '2022:03:27 09:04:12' },
  { filename: '3.March\\Photos\\March 27-3.jpeg', lat: 40.362961, lng: -104.984061, date: '2022:03:27 09:38:14' },
  { filename: '3.March\\Photos\\March 27-4.jpg', lat: 39.055625, lng: -104.853675, date: '2022:03:27 11:48:27' },
  { filename: '3.March\\Photos\\March 27-5.jpeg', lat: 39.055456, lng: -104.853631, date: '2022:03:27 11:52:21' },
  { filename: '3.March\\Photos\\March 27-6.jpeg', lat: 38.3424, lng: -104.623558, date: '2022:03:27 13:09:03' },
  { filename: '3.March\\Photos\\March 28-1.jpeg', lat: 32.631375, lng: -96.815711, date: '2022:03:28 09:49:17' },
  { filename: '3.March\\Photos\\March 28-2.jpeg', lat: 32.592761, lng: -96.819022, date: '2022:03:28 10:26:55' },
  { filename: '3.March\\Photos\\March 28-3.jpeg', lat: 32.592942, lng: -96.819, date: '2022:03:28 10:27:07' },
  { filename: '3.March\\Photos\\March 28-5.jpeg', lat: 35.163525, lng: -101.527336, date: '2022:03:28 20:12:20' },
  { filename: '3.March\\Photos\\March 28-6.jpeg', lat: 35.210442, lng: -102.240075, date: '2022:03:28 23:07:28' },
  { filename: '3.March\\Photos\\March 28-7.jpeg', lat: 35.210464, lng: -102.241844, date: '2022:03:28 23:07:32' },
  { filename: '3.March\\Photos\\March 29-1.jpeg', lat: 36.957633, lng: -108.736083, date: '2022:03:29 11:10:19' },
  { filename: '3.March\\Photos\\March 29-2.jpeg', lat: 36.958875, lng: -108.736542, date: '2022:03:29 11:10:24' },
  { filename: '3.March\\Photos\\March 29-3.jpeg', lat: 36.978397, lng: -108.743722, date: '2022:03:29 11:11:42' },
  { filename: '3.March\\Photos\\March 29-4.jpeg', lat: 38.561661, lng: -109.547286, date: '2022:03:29 14:18:41' },
  { filename: '3.March\\Photos\\March 29-5.jpeg', lat: 39.222839, lng: -110.338647, date: '2022:03:29 16:02:05' },
  { filename: '3.March\\Photos\\March 29-6.jpeg', lat: 39.2231, lng: -110.338647, date: '2022:03:29 16:02:05' },
  { filename: '3.March\\Photos\\March 29-7.jpeg', lat: 39.692392, lng: -110.858872, date: '2022:03:29 16:52:56' },
  { filename: '3.March\\Photos\\March 29-8.jpeg', lat: 39.702386, lng: -110.868667, date: '2022:03:29 16:54:05' },
  { filename: '3.March\\Photos\\March 29-9.jpeg', lat: 39.950192, lng: -111.217483, date: '2022:03:29 17:30:53' },
  { filename: '3.March\\Photos\\March 29-10.jpeg', lat: 39.950467, lng: -111.217772, date: '2022:03:29 17:30:56' },
  { filename: '3.March\\Photos\\March 29-11.jpeg', lat: 39.950481, lng: -111.217628, date: '2022:03:29 17:33:27' },
  { filename: '3.March\\Photos\\March 30-1.jpeg', lat: 45.692344, lng: -121.686097, date: '2022:03:30 11:15:06' },
  { filename: '3.March\\Photos\\March 30-2.jpeg', lat: 45.691458, lng: -121.687264, date: '2022:03:30 11:15:12' },
  { filename: '3.March\\Photos\\March 31-1.jpeg', lat: 47.937175, lng: -122.246261, date: '2022:03:31 10:48:26' },
  { filename: '3.March\\Photos\\March 31-2.jpeg', lat: 48.598919, lng: -122.344217, date: '2022:03:31 17:06:55' },
  { filename: '4.April\\Photos\\April 2-1.jpeg', lat: 42.410339, lng: -113.313867, date: '2022:04:02 16:20:57' },
  { filename: '4.April\\Photos\\April 2-2.jpeg', lat: 42.381569, lng: -113.280425, date: '2022:04:02 16:23:23' },
  { filename: '4.April\\Photos\\April 2-3.jpeg', lat: 42.346183, lng: -113.239067, date: '2022:04:02 16:26:23' },
  { filename: '4.April\\Photos\\April 2-4.jpeg', lat: 41.728578, lng: -112.244483, date: '2022:04:02 17:32:21' },
  { filename: '4.April\\Photos\\April 2-5.jpeg', lat: 41.721517, lng: -112.2312, date: '2022:04:02 17:33:08' },
  { filename: '4.April\\Photos\\April 2-6.jpeg', lat: 41.720464, lng: -112.228744, date: '2022:04:02 17:33:16' },
  { filename: '4.April\\Photos\\April 2-7.jpeg', lat: 41.719792, lng: -112.227164, date: '2022:04:02 17:33:21' },
  { filename: '4.April\\Photos\\April 2-8.jpeg', lat: 41.576492, lng: -112.071944, date: '2022:04:02 17:45:36' },
  { filename: '4.April\\Photos\\April 2-9.jpeg', lat: 41.155461, lng: -111.988419, date: '2022:04:02 18:14:34' },
  { filename: '4.April\\Photos\\April 2-10.jpeg', lat: 41.049586, lng: -111.611528, date: '2022:04:02 18:37:50' },
  { filename: '4.April\\Photos\\April 4.jpeg', lat: 35.494236, lng: -106.725914, date: '2022:04:04 22:36:50' },
  { filename: '4.April\\Photos\\April 6-2.jpeg', lat: 45.620053, lng: -122.673928, date: '2022:04:06 19:38:48' },
  { filename: '4.April\\Photos\\April 18.jpeg', lat: 35.008472, lng: -106.064658, date: '2022:04:18 14:01:04' },
  { filename: '4.April\\Photos\\April 19.jpeg', lat: 45.760067, lng: -120.140114, date: '2022:04:19 19:51:13' },
  { filename: '4.April\\Photos\\April 20-1.jpeg', lat: 46.392289, lng: -122.905983, date: '2022:04:20 18:36:54' },
  { filename: '4.April\\Photos\\April 20-2.jpeg', lat: 48.187053, lng: -122.195136, date: '2022:04:20 23:50:31' },
  { filename: '4.April\\Photos\\April 21-1.jpeg', lat: 47.922058, lng: -122.269372, date: '2022:04:21 12:52:01' },
  { filename: '4.April\\Photos\\April 21-2.jpeg', lat: 47.922153, lng: -122.270019, date: '2022:04:21 12:52:04' },
  { filename: '4.April\\Photos\\April 21-3.jpeg', lat: 47.650714, lng: -122.322661, date: '2022:04:21 14:02:23' },
  { filename: '4.April\\Photos\\April 22.jpeg', lat: 45.537319, lng: -122.480828, date: '2022:04:22 09:03:21' },
  { filename: '4.April\\Photos\\April 23-1.jpeg', lat: 40.531942, lng: -111.892167, date: '2022:04:23 12:10:22' },
  { filename: '4.April\\Photos\\April 23-2.jpeg', lat: 40.531319, lng: -111.891975, date: '2022:04:23 12:10:24' },
  { filename: '4.April\\Photos\\April 23-3.jpeg', lat: 40.528186, lng: -111.891419, date: '2022:04:23 12:10:37' },
  { filename: '4.April\\Photos\\April 23-4.jpeg', lat: 40.527675, lng: -111.891372, date: '2022:04:23 12:10:39' },
  { filename: '4.April\\Photos\\April 23-5.jpeg', lat: 40.005731, lng: -111.492058, date: '2022:04:23 12:59:36' },
  { filename: '4.April\\Photos\\April 23-6.jpeg', lat: 39.995742, lng: -111.449264, date: '2022:04:23 13:02:17' },
  { filename: '4.April\\Photos\\April 25-1.jpeg', lat: 32.630978, lng: -96.815217, date: '2022:04:25 11:38:02' },
  { filename: '4.April\\Photos\\April 25-2.jpeg', lat: 32.612153, lng: -96.824211, date: '2022:04:25 12:49:40' },
  { filename: '4.April\\Photos\\April 25-3.jpeg', lat: 32.612033, lng: -96.824044, date: '2022:04:25 12:49:49' },
  { filename: '4.April\\Photos\\April 25-4.jpeg', lat: 32.612019, lng: -96.824089, date: '2022:04:25 12:50:03' },
  { filename: '4.April\\Photos\\April 26.jpeg', lat: 32.632758, lng: -96.817061, date: '2022:04:26 07:20:27' },
  { filename: '4.April\\Photos\\April 28-1.jpeg', lat: 30.166997, lng: -95.426772, date: '2022:04:28 17:38:32' },
  { filename: '4.April\\Photos\\April 28-2.jpeg', lat: 30.167008, lng: -95.426728, date: '2022:04:28 17:38:45' },
  { filename: '4.April\\Photos\\April 28-3.jpeg', lat: 30.16705, lng: -95.426772, date: '2022:04:28 17:42:07' },
  { filename: '4.April\\Photos\\April 28-4.jpeg', lat: 30.167022, lng: -95.426736, date: '2022:04:28 17:43:10' },
  { filename: '4.April\\Photos\\April 28-5.jpeg', lat: 30.167039, lng: -95.426781, date: '2022:04:28 17:44:33' },
  { filename: '5.May\\Photos\\May 12.jpeg', lat: 33.971969, lng: -117.349244, date: '2022:05:12 05:30:49' },
  { filename: '5.May\\Photos\\May 13-2.jpeg', lat: 33.388061, lng: -111.964347, date: '2022:05:13 16:45:38' },
  { filename: '5.May\\Photos\\May 13-3.jpeg', lat: 33.388214, lng: -111.965736, date: '2022:05:13 16:45:46' },
  { filename: '5.May\\Photos\\May 13-4.jpeg', lat: 33.388006, lng: -111.967125, date: '2022:05:13 16:45:55' },
  { filename: '5.May\\Photos\\May 13-5.jpeg', lat: 33.387753, lng: -111.967544, date: '2022:05:13 16:45:58' },
  { filename: '5.May\\Photos\\May 13-6.jpeg', lat: 32.887192, lng: -111.687089, date: '2022:05:13 17:39:49' },
  { filename: '5.May\\Photos\\May 13-7.jpeg', lat: 32.883786, lng: -111.687119, date: '2022:05:13 17:40:03' },
  { filename: '5.May\\Photos\\May 13-8.jpeg', lat: 32.881383, lng: -111.687125, date: '2022:05:13 17:40:14' },
  { filename: '5.May\\Photos\\May 14.jpeg', lat: 32.335186, lng: -111.045258, date: '2022:05:14 07:18:19' },
  { filename: '5.May\\Photos\\May 16-1.jpeg', lat: 32.632422, lng: -96.816094, date: '2022:05:16 05:46:46' },
  { filename: '5.May\\Photos\\May 16-3.jpeg', lat: 32.7864, lng: -96.805519, date: '2022:05:16 12:23:22' },
  { filename: '5.May\\Photos\\May 17-1.jpeg', lat: 39.727322, lng: -104.844772, date: '2022:05:17 13:54:41' },
  { filename: '5.May\\Photos\\May 18-1.jpeg', lat: 39.078492, lng: -108.534753, date: '2022:05:18 08:21:07' },
  { filename: '5.May\\Photos\\May 18-2.jpeg', lat: 39.116097, lng: -108.395339, date: '2022:05:18 10:20:03' },
  { filename: '5.May\\Photos\\May 20-1.jpeg', lat: 32.711164, lng: -96.822608, date: '2022:05:20 16:52:33' },
  { filename: '5.May\\Photos\\May 23-1.jpeg', lat: 47.473417, lng: -121.904708, date: '2022:05:23 19:12:37' },
  { filename: '5.May\\Photos\\May 23-2.jpeg', lat: 47.511019, lng: -121.860817, date: '2022:05:23 19:17:17' },
  { filename: '5.May\\Photos\\May 23-3.jpeg', lat: 47.510972, lng: -121.859117, date: '2022:05:23 19:17:21' },
  { filename: '5.May\\Photos\\May 23-4.jpeg', lat: 47.510589, lng: -121.831453, date: '2022:05:23 19:18:49' },
  { filename: '5.May\\Photos\\May 23-5.jpeg', lat: 47.486417, lng: -121.794922, date: '2022:05:23 19:21:15' },
  { filename: '5.May\\Photos\\May 23-6.jpeg', lat: 47.485642, lng: -121.794144, date: '2022:05:23 19:21:20' },
  { filename: '5.May\\Photos\\May 23-7.jpeg', lat: 47.455036, lng: -121.702422, date: '2022:05:23 19:26:38' },
  { filename: '5.May\\Photos\\May 24-3.jpeg', lat: 44.025569, lng: -116.951172, date: '2022:05:24 19:51:28' },
  { filename: '5.May\\Photos\\May 26-1.jpeg', lat: 38.158317, lng: -102.723464, date: '2022:05:26 04:45:52' },
  { filename: '5.May\\Photos\\May 26-2.jpeg', lat: 35.266017, lng: -101.834175, date: '2022:05:26 14:12:37' },
  { filename: '5.May\\Photos\\May 26-4.jpeg', lat: 32.631908, lng: -96.816383, date: '2022:05:26 21:00:25' },
  { filename: '5.May\\Photos\\May 26-5.jpeg', lat: 32.632122, lng: -96.816489, date: '2022:05:26 21:06:29' },
  { filename: '5.May\\Photos\\May 30.jpeg', lat: 29.88275, lng: -97.935006, date: '2022:05:30 10:48:36' },
  { filename: '6.June\\Photos\\June 6-1.jpeg', lat: 30.469319, lng: -87.2258, date: '2022:06:06 13:44:27' },
  { filename: '6.June\\Photos\\June 6-2.jpeg', lat: 30.507669, lng: -87.161147, date: '2022:06:06 14:58:17' },
  { filename: '6.June\\Photos\\June 7-1.jpeg', lat: 28.487842, lng: -81.405983, date: '2022:06:07 06:48:17' },
  { filename: '6.June\\Photos\\June 11-1.jpeg', lat: 28.918061, lng: -81.296228, date: '2022:06:11 21:02:58' },
  { filename: '6.June\\Photos\\June 15-2.jpeg', lat: 34.975661, lng: -81.932992, date: '2022:06:15 21:21:28' },
  { filename: '6.June\\Photos\\June 18-1.jpeg', lat: 34.851967, lng: -78.262336, date: '2022:06:18 17:23:55' },
  { filename: '6.June\\Photos\\June 21-1.jpeg', lat: 34.331908, lng: -86.314544, date: '2022:06:21 16:24:43' },
  { filename: '6.June\\Photos\\June 21-2.jpeg', lat: 34.331269, lng: -86.3145, date: '2022:06:21 16:24:52' },
  { filename: '6.June\\Photos\\June 21-3.jpg', lat: 34.331269, lng: -86.3145, date: '2022:06:21 16:24:52' },
  { filename: '6.June\\Photos\\June 21-5.jpeg', lat: 33.519764, lng: -86.818406, date: '2022:06:21 20:52:55' },
  { filename: '6.June\\Photos\\June 21-6.jpeg', lat: 33.523981, lng: -86.808189, date: '2022:06:21 20:53:38' },
  { filename: '6.June\\Photos\\June 21-7.jpeg', lat: 33.524478, lng: -86.806961, date: '2022:06:21 20:53:43' },
  { filename: '6.June\\Photos\\June 23-1.jpeg', lat: 31.178181, lng: -85.400375, date: '2022:06:23 07:11:31' },
  { filename: '6.June\\Photos\\June 23-2.jpeg', lat: 30.911569, lng: -87.967658, date: '2022:06:23 14:38:09' },
  { filename: '6.June\\Photos\\June 23-3.jpeg', lat: 30.912833, lng: -87.965164, date: '2022:06:23 14:38:20' },
  { filename: '6.June\\Photos\\June 23-4.jpeg', lat: 30.913211, lng: -87.964508, date: '2022:06:23 14:38:24' },
  { filename: '6.June\\Photos\\June 23-5.jpeg', lat: 30.913822, lng: -87.963394, date: '2022:06:23 14:38:28' },
  { filename: '6.June\\Photos\\June 25-1.jpeg', lat: 35.233689, lng: -95.594658, date: '2022:06:25 17:31:03' },
  { filename: '7.July\\Photos\\July 3-1.jpeg', lat: 32.630753, lng: -96.816017, date: '2022:07:03 10:43:42' },
  { filename: '7.July\\Photos\\July 5-1.jpeg', lat: 34.99155, lng: -117.542283, date: '2022:07:05 13:47:18' },
  { filename: '7.July\\Photos\\july 5-2.jpeg', lat: 39.491222, lng: -119.794517, date: '2022:07:05 22:28:02' },
  { filename: '7.July\\Photos\\July 10-1.jpeg', lat: 37.556192, lng: -102.620317, date: '2022:07:10 22:43:40' },
  { filename: '7.July\\Photos\\July 11-1.jpeg', lat: 41.536933, lng: -109.931, date: '2022:07:11 10:34:01' },
  { filename: '7.July\\Photos\\July 11-2.jpeg', lat: 41.5271, lng: -109.950911, date: '2022:07:11 10:35:13' },
  { filename: '7.July\\Photos\\July 11-5.jpeg', lat: 40.620158, lng: -111.894753, date: '2022:07:11 16:18:01' },
  { filename: '7.July\\Photos\\July 12-1.jpeg', lat: 31.897767, lng: -106.582992, date: '2022:07:12 16:48:03' },
  { filename: '7.July\\Photos\\July 12-2.jpeg', lat: 31.897767, lng: -106.582992, date: '2022:07:12 16:48:03' },
  { filename: '7.July\\Photos\\July 16-1.jpeg', lat: 35.378131, lng: -97.496911, date: '2022:07:16 06:43:46' },
  { filename: '7.July\\Photos\\July 17-1.jpeg', lat: 37.213653, lng: -93.381553, date: '2022:07:17 16:24:22' },
  { filename: '7.July\\Photos\\July 17-2.jpeg', lat: 37.213608, lng: -93.381547, date: '2022:07:17 16:24:49' },
  { filename: '7.July\\Photos\\July 17-3.jpeg', lat: 37.213608, lng: -93.381547, date: '2022:07:17 16:24:53' },
  { filename: '7.July\\Photos\\July 18-1.jpeg', lat: 38.941636, lng: -95.245339, date: '2022:07:18 17:15:50' },
  { filename: '7.July\\Photos\\July 18-2.jpeg', lat: 38.941647, lng: -95.245317, date: '2022:07:18 17:15:57' },
  { filename: '7.July\\Photos\\July 18-3.jpeg', lat: 38.941761, lng: -95.245086, date: '2022:07:18 17:48:27' },
  { filename: '7.July\\Photos\\July 18-4.jpeg', lat: 38.941764, lng: -95.244836, date: '2022:07:18 17:59:10' },
  { filename: '7.July\\Photos\\July 30-1.jpeg', lat: 32.632008, lng: -96.816147, date: '2022:07:30 02:45:59' },
  { filename: '7.July\\Photos\\July 30-2.jpeg', lat: 32.632028, lng: -96.816156, date: '2022:07:30 02:46:09' },
  { filename: '7.July\\Photos\\July 30-3.jpeg', lat: 32.632028, lng: -96.816156, date: '2022:07:30 02:46:20' },
  { filename: '7.July\\Photos\\July 30-4.jpeg', lat: 32.632022, lng: -96.816156, date: '2022:07:30 02:46:31' },
  { filename: '7.July\\Photos\\July 30-5.jpeg', lat: 32.632019, lng: -96.816156, date: '2022:07:30 02:46:34' },
  { filename: '7.July\\Photos\\July 30-6.jpeg', lat: 32.632011, lng: -96.816156, date: '2022:07:30 02:46:41' },
  { filename: '7.July\\Photos\\July 30-7.jpeg', lat: 32.632014, lng: -96.816161, date: '2022:07:30 02:46:47' },
  { filename: '7.July\\Photos\\July 30-8.jpeg', lat: 32.632028, lng: -96.816139, date: '2022:07:30 02:46:59' },
  { filename: '7.July\\Photos\\July 30-9.jpeg', lat: 32.632014, lng: -96.816117, date: '2022:07:30 02:48:58' },
  { filename: '7.July\\Photos\\July 30-10.jpeg', lat: 32.632019, lng: -96.816139, date: '2022:07:30 02:49:01' },
  { filename: '7.July\\Photos\\July 30-11.jpeg', lat: 32.632019, lng: -96.816147, date: '2022:07:30 02:49:32' },
  { filename: '7.July\\Photos\\July 30-12.jpeg', lat: 32.631967, lng: -96.816139, date: '2022:07:30 02:52:28' },
  { filename: '7.July\\Photos\\July 30-13.jpeg', lat: 35.492828, lng: -97.524619, date: '2022:07:30 11:51:24' },
  { filename: '8.August\\Photos\\Aug 1-1.jpeg', lat: 39.044986, lng: -95.682625, date: '2022:08:01 21:31:39' },
  { filename: '8.August\\Photos\\Aug 1-2.jpeg', lat: 39.044994, lng: -95.682625, date: '2022:08:01 21:31:48' },
  { filename: '8.August\\Photos\\Aug 2-1.jpeg', lat: 39.05305, lng: -96.754142, date: '2022:08:02 13:14:14' },
  { filename: '8.August\\Photos\\Aug 2-2.jpeg', lat: 37.693194, lng: -97.320725, date: '2022:08:02 16:23:11' },
  { filename: '8.August\\Photos\\Aug 8-2.jpeg', lat: 36.412475, lng: -99.384414, date: '2022:08:08 13:23:38' },
  { filename: '8.August\\Photos\\Aug 9-1.jpeg', lat: 32.79395, lng: -96.683228, date: '2022:08:09 20:40:44' },
  { filename: '8.August\\Photos\\Aug 9-2.jpeg', lat: 32.793564, lng: -96.683542, date: '2022:08:09 21:05:31' },
  { filename: '8.August\\Photos\\Aug 10-1.jpeg', lat: 32.739681, lng: -97.017014, date: '2022:08:10 15:41:35' },
  { filename: '8.August\\Photos\\Aug 14-1.jpeg', lat: 33.785983, lng: -98.162614, date: '2022:08:14 20:18:51' },
  { filename: '8.August\\Photos\\Aug 14-2.jpeg', lat: 33.785983, lng: -98.162614, date: '2022:08:14 20:18:51' },
  { filename: '8.August\\Photos\\Aug 14-3.jpeg', lat: 33.786633, lng: -98.163719, date: '2022:08:14 20:18:54' },
  { filename: '8.August\\Photos\\Aug 14-4.jpeg', lat: 33.78695, lng: -98.164275, date: '2022:08:14 20:18:56' },
  { filename: '8.August\\Photos\\Aug 14-5.jpeg', lat: 33.787278, lng: -98.164842, date: '2022:08:14 20:18:58' },
  { filename: '8.August\\Photos\\Aug 15-1.jpeg', lat: 36.101047, lng: -115.163581, date: '2022:08:15 16:05:47' },
  { filename: '8.August\\Photos\\Aug 15-2.jpeg', lat: 36.10105, lng: -115.163589, date: '2022:08:15 16:05:50' },
  { filename: '8.August\\Photos\\Aug 15-3.jpeg', lat: 36.116772, lng: -115.261856, date: '2022:08:15 17:11:03' },
  { filename: '8.August\\Photos\\Aug 15-4.jpeg', lat: 36.115775, lng: -115.180939, date: '2022:08:15 20:27:34' },
  { filename: '8.August\\Photos\\Aug 15-5.jpeg', lat: 36.112889, lng: -115.173094, date: '2022:08:15 20:30:11' },
  { filename: '8.August\\Photos\\Aug 15-7.jpeg', lat: 36.114269, lng: -115.17395, date: '2022:08:15 20:38:58' },
  { filename: '8.August\\Photos\\Aug 15-8.jpeg', lat: 36.114206, lng: -115.174019, date: '2022:08:15 20:48:24' },
  { filename: '8.August\\Photos\\Aug 15-9.jpeg', lat: 36.115831, lng: -115.173592, date: '2022:08:15 21:23:37' },
  { filename: '8.August\\Photos\\Aug 16-1.jpeg', lat: 36.158117, lng: -115.161178, date: '2022:08:16 08:38:45' },
  { filename: '8.August\\Photos\\Aug 17-1.jpeg', lat: 31.774278, lng: -106.337417, date: '2022:08:17 12:13:01' },
  { filename: '8.August\\Photos\\Aug 18-1.jpeg', lat: 30.482861, lng: -97.677169, date: '2022:08:18 09:11:58' },
  { filename: '8.August\\Photos\\Aug 30-1.jpeg', lat: 39.814158, lng: -105.130683, date: '2022:08:30 12:22:56' },
  { filename: '8.August\\Photos\\Aug 30-2.jpeg', lat: 39.814164, lng: -105.130669, date: '2022:08:30 12:23:28' },
  { filename: '8.August\\Photos\\Aug 30-3.jpeg', lat: 39.814189, lng: -105.130639, date: '2022:08:30 12:23:39' },
  { filename: '8.August\\Photos\\Aug 30-4.jpeg', lat: 39.8142, lng: -105.130644, date: '2022:08:30 12:23:45' },
  { filename: '8.August\\Photos\\Aug 30-5.jpeg', lat: 39.814217, lng: -105.130653, date: '2022:08:30 12:23:52' },
  { filename: '8.August\\Photos\\Aug 31-1.jpeg', lat: 39.570789, lng: -107.460122, date: '2022:08:31 10:32:54' },
  { filename: '8.August\\Photos\\Aug 31-4.jpeg', lat: 39.679131, lng: -106.648256, date: '2022:08:31 11:36:31' },
  { filename: '8.August\\Photos\\Aug 31-5.jpeg', lat: 39.642553, lng: -106.571564, date: '2022:08:31 11:54:20' },
  { filename: '8.August\\Photos\\Aug 31-6.jpeg', lat: 39.674186, lng: -105.960319, date: '2022:08:31 12:58:24' },
  { filename: '8.August\\Photos\\Aug 31-7.jpeg', lat: 39.678964, lng: -105.914956, date: '2022:08:31 13:02:54' },
  { filename: '8.August\\Photos\\Aug 31-8.jpeg', lat: 39.678964, lng: -105.914956, date: '2022:08:31 13:02:57' },
  { filename: '9.September\\Photos\\Sept 4-1.jpeg', lat: 35.686572, lng: -88.858033, date: '2022:09:04 14:15:20' },
  { filename: '9.September\\Photos\\Sept 4-2.jpeg', lat: 34.537772, lng: -86.911142, date: '2022:09:04 18:48:42' },
  { filename: '9.September\\Photos\\Sept 6-2.jpeg', lat: 34.279847, lng: -83.852403, date: '2022:09:06 13:42:40' },
  { filename: '9.September\\Photos\\Sept 7-1.jpeg', lat: 34.124486, lng: -84.75055, date: '2022:09:07 10:22:36' },
  { filename: '9.September\\Photos\\Sept 8-1.jpeg', lat: 36.256019, lng: -86.715972, date: '2022:09:08 20:44:41' },
  { filename: '9.September\\Photos\\Sept 17-1.jpeg', lat: 35.353, lng: -109.057817, date: '2022:09:17 19:17:25' },
  { filename: '9.September\\Photos\\sept 17-2.jpeg', lat: 35.266717, lng: -112.725281, date: '2022:09:17 23:29:28' }
];

// Photos without GPS data (not mapped):
//   - 2.February\Photos\._Feb 15.jpeg
//   - 2.February\Photos\._Feb 17.jpeg
//   - 2.February\Photos\._Feb 21-1.jpeg
//   - 2.February\Photos\._Feb 21-2.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2019.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2020.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2021.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2022.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2023.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2024.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2025.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2026.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2027.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2028.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2029.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2030.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2031.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2032.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2033.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2034.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2035.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2036.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2037.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2038.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2039.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2040.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2041.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2042.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2043.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2044.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2045.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2046.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2047.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2048.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2049.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2050.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2051.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2052.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2053.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2054.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2055.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2056.jpeg
//   - 2.February\Photos\Feb 17 Study Sheets\._IMG_2057.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2074.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2085.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2086.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2087.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2088.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2089.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2090.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2091.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2092.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2093.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2094.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2095.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2096.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2097.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2098.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2099.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2100.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2101.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2102.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2103.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2104.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2105.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2106.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2107.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2108.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2109.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2110.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2111.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2112.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2113.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2114.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2115.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2116.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2117.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2118.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2119.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2120.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2121.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2122.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2123.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2124.jpeg
//   - 2.February\Photos\Feb 28 Study Material\._IMG_2125.jpeg
//   - 3.March\Photos\._March 8-1.jpeg
//   - 3.March\Photos\._March 8-2.jpeg
//   - 3.March\Photos\._March 9.jpeg
//   - 3.March\Photos\._March 10-1.jpeg
//   - 3.March\Photos\._March 10-2.jpeg
//   - 3.March\Photos\._March 10-3.jpeg
//   - 3.March\Photos\._March 10-4.jpeg
//   - 3.March\Photos\._March 10-5.jpeg
//   - 3.March\Photos\._March 12-1.jpeg
//   - 3.March\Photos\._March 12-2.jpeg
//   - 3.March\Photos\._March 13.jpeg
//   - 3.March\Photos\._March 14-1.jpeg
//   - 3.March\Photos\._March 14-3.jpeg
//   - 3.March\Photos\._March 14-4.jpeg
//   - 3.March\Photos\._March 14-5.jpeg
//   - 3.March\Photos\._March 14-6.jpeg
//   - 3.March\Photos\._March 14-7.jpeg
//   - 3.March\Photos\._March 14-9.jpeg
//   - 3.March\Photos\._March 14-10.jpeg
//   - 3.March\Photos\._March 14-11.jpeg
//   - 3.March\Photos\._March 15-2.jpeg
//   - 3.March\Photos\._March 15-3.jpeg
//   - 3.March\Photos\._March 15-4.jpeg
//   - 3.March\Photos\._March 15-6.jpeg
//   - 3.March\Photos\._March 15-7.jpeg
//   - 3.March\Photos\._March 15-8.jpeg
//   - 3.March\Photos\._March 15-9.jpeg
//   - 3.March\Photos\._March 15-10.jpeg
//   - 3.March\Photos\._March 16-1.jpeg
//   - 3.March\Photos\._March 16-2.jpeg
//   - 3.March\Photos\._March 16-3.jpeg
//   - 3.March\Photos\._March 16-4.jpeg
//   - 3.March\Photos\._March 16-5.jpeg
//   - 3.March\Photos\._March 16-6.jpeg
//   - 3.March\Photos\._March 16-7.jpeg
//   - 3.March\Photos\._March 16-8.jpeg
//   - 3.March\Photos\._March 16-9.jpeg
//   - 3.March\Photos\._March 16-10.jpeg
//   - 3.March\Photos\._March 16-11.jpeg
//   - 3.March\Photos\._March 16-12.jpeg
//   - 3.March\Photos\._March 16-13.jpeg
//   - 3.March\Photos\._March 16-14.jpeg
//   - 3.March\Photos\._March 16-15.jpeg
//   - 3.March\Photos\._March 16-16.jpeg
//   - 3.March\Photos\._March 17-2.jpeg
//   - 3.March\Photos\._March 17-3.jpeg
//   - 3.March\Photos\._March 17-4.jpeg
//   - 3.March\Photos\._March 17-5.jpeg
//   - 3.March\Photos\._March 18.jpeg
//   - 3.March\Photos\._March 19-1.jpeg
//   - 3.March\Photos\._March 19-2.jpeg
//   - 3.March\Photos\._March 21.jpeg
//   - 3.March\Photos\._March 23.jpeg
//   - 3.March\Photos\._March 24.jpeg
//   - 3.March\Photos\._March 25-1.jpeg
//   - 3.March\Photos\._March 25-2.jpg
//   - 3.March\Photos\._March 25-3.jpeg
//   - 3.March\Photos\._March 26.jpeg
//   - 3.March\Photos\._March 27-1.jpeg
//   - 3.March\Photos\._March 27-2.jpeg
//   - 3.March\Photos\._March 27-3.jpeg
//   - 3.March\Photos\._March 27-4.jpg
//   - 3.March\Photos\._March 27-5.jpeg
//   - 3.March\Photos\._March 27-6.jpeg
//   - 3.March\Photos\._March 28-1.jpeg
//   - 3.March\Photos\._March 28-2.jpeg
//   - 3.March\Photos\._March 28-3.jpeg
//   - 3.March\Photos\._March 28-4.jpeg
//   - 3.March\Photos\._March 28-5.jpeg
//   - 3.March\Photos\._March 28-6.jpeg
//   - 3.March\Photos\._March 28-7.jpeg
//   - 3.March\Photos\._March 29-1.jpeg
//   - 3.March\Photos\._March 29-2.jpeg
//   - 3.March\Photos\._March 29-3.jpeg
//   - 3.March\Photos\._March 29-4.jpeg
//   - 3.March\Photos\._March 29-5.jpeg
//   - 3.March\Photos\._March 29-6.jpeg
//   - 3.March\Photos\._March 29-7.jpeg
//   - 3.March\Photos\._March 29-8.jpeg
//   - 3.March\Photos\._March 29-9.jpeg
//   - 3.March\Photos\._March 29-10.jpeg
//   - 3.March\Photos\._March 29-11.jpeg
//   - 3.March\Photos\._March 30-1.jpeg
//   - 3.March\Photos\._March 30-2.jpeg
//   - 3.March\Photos\._March 31-1.jpeg
//   - 3.March\Photos\._March 31-2.jpeg
//   - 3.March\Photos\March 5\._IMG_2133.jpeg
//   - 3.March\Photos\March 5\._IMG_2134.jpeg
//   - 3.March\Photos\March 5\._IMG_2135.jpeg
//   - 3.March\Photos\March 5\._IMG_2136.jpeg
//   - 3.March\Photos\March 13.jpeg
//   - 3.March\Photos\March 21.jpeg
//   - 3.March\Photos\March 27-1.jpeg
//   - 3.March\Photos\March 28-4.jpeg
//   - 4.April\Photos\._April 2-1.jpeg
//   - 4.April\Photos\._April 2-2.jpeg
//   - 4.April\Photos\._April 2-3.jpeg
//   - 4.April\Photos\._April 2-4.jpeg
//   - 4.April\Photos\._April 2-5.jpeg
//   - 4.April\Photos\._April 2-6.jpeg
//   - 4.April\Photos\._April 2-7.jpeg
//   - 4.April\Photos\._April 2-8.jpeg
//   - 4.April\Photos\._April 2-9.jpeg
//   - 4.April\Photos\._April 2-10.jpeg
//   - 4.April\Photos\._April 3.jpeg
//   - 4.April\Photos\._April 4.jpeg
//   - 4.April\Photos\._April 5.jpeg
//   - 4.April\Photos\._April 6-2.jpeg
//   - 4.April\Photos\._April 13.JPG
//   - 4.April\Photos\._April 18.jpeg
//   - 4.April\Photos\._April 19.jpeg
//   - 4.April\Photos\._April 20-1.jpeg
//   - 4.April\Photos\._April 20-2.jpeg
//   - 4.April\Photos\._April 21-1.jpeg
//   - 4.April\Photos\._April 21-2.jpeg
//   - 4.April\Photos\._April 21-3.jpeg
//   - 4.April\Photos\._April 21-4.JPG
//   - 4.April\Photos\._April 22.jpeg
//   - 4.April\Photos\._April 23-1.jpeg
//   - 4.April\Photos\._April 23-2.jpeg
//   - 4.April\Photos\._April 23-3.jpeg
//   - 4.April\Photos\._April 23-4.jpeg
//   - 4.April\Photos\._April 23-5.jpeg
//   - 4.April\Photos\._April 23-6.jpeg
//   - 4.April\Photos\._April 23-7.jpeg
//   - 4.April\Photos\._April 25-1.jpeg
//   - 4.April\Photos\._April 25-2.jpeg
//   - 4.April\Photos\._April 25-3.jpeg
//   - 4.April\Photos\._April 25-4.jpeg
//   - 4.April\Photos\._April 26.jpeg
//   - 4.April\Photos\._April 28-1.jpeg
//   - 4.April\Photos\._April 28-2.jpeg
//   - 4.April\Photos\._April 28-3.jpeg
//   - 4.April\Photos\._April 28-4.jpeg
//   - 4.April\Photos\._April 28-5.jpeg
//   - 4.April\Photos\April 3.jpeg
//   - 4.April\Photos\April 5.jpeg
//   - 4.April\Photos\April 13.JPG
//   - 4.April\Photos\April 21-4.JPG
//   - 4.April\Photos\April 23-7.jpeg
//   - 5.May\Photos\._May 12.jpeg
//   - 5.May\Photos\._May 13-2.jpeg
//   - 5.May\Photos\._May 13-3.jpeg
//   - 5.May\Photos\._May 13-4.jpeg
//   - 5.May\Photos\._May 13-5.jpeg
//   - 5.May\Photos\._May 13-6.jpeg
//   - 5.May\Photos\._May 13-7.jpeg
//   - 5.May\Photos\._May 13-8.jpeg
//   - 5.May\Photos\._May 14.jpeg
//   - 5.May\Photos\._May 16-1.jpeg
//   - 5.May\Photos\._May 16-2.jpeg
//   - 5.May\Photos\._May 16-3.jpeg
//   - 5.May\Photos\._May 17-1.jpeg
//   - 5.May\Photos\._May 17-2.PNG
//   - 5.May\Photos\._May 18-1.jpeg
//   - 5.May\Photos\._May 18-2.jpeg
//   - 5.May\Photos\._May 20-1.jpeg
//   - 5.May\Photos\._May 22.jpeg
//   - 5.May\Photos\._May 23-1.jpeg
//   - 5.May\Photos\._May 23-2.jpeg
//   - 5.May\Photos\._May 23-3.jpeg
//   - 5.May\Photos\._May 23-4.jpeg
//   - 5.May\Photos\._May 23-5.jpeg
//   - 5.May\Photos\._May 23-6.jpeg
//   - 5.May\Photos\._May 23-7.jpeg
//   - 5.May\Photos\._May 24-1.PNG
//   - 5.May\Photos\._May 24-3.jpeg
//   - 5.May\Photos\._May 25-1.jpeg
//   - 5.May\Photos\._May 26-1.jpeg
//   - 5.May\Photos\._May 26-2.jpeg
//   - 5.May\Photos\._May 26-4.jpeg
//   - 5.May\Photos\._May 26-5.jpeg
//   - 5.May\Photos\._May 30.jpeg
//   - 5.May\Photos\May 16-2.jpeg
//   - 5.May\Photos\May 17-2.PNG
//   - 5.May\Photos\May 22.jpeg
//   - 5.May\Photos\May 24-1.PNG
//   - 5.May\Photos\May 25-1.jpeg
//   - 5.May\Schedules\._May 5.jpeg
//   - 5.May\Schedules\May 5.jpeg
//   - 6.June\Photos\._June 6-1.jpeg
//   - 6.June\Photos\._June 6-2.jpeg
//   - 6.June\Photos\._June 7-1.jpeg
//   - 6.June\Photos\._June 11-1.jpeg
//   - 6.June\Photos\._June 14-1.jpeg
//   - 6.June\Photos\._June 15-2.jpeg
//   - 6.June\Photos\._June 16-1.JPG
//   - 6.June\Photos\._June 18-1.jpeg
//   - 6.June\Photos\._June 21-1.jpeg
//   - 6.June\Photos\._June 21-2.jpeg
//   - 6.June\Photos\._June 21-3.jpg
//   - 6.June\Photos\._June 21-4.jpeg
//   - 6.June\Photos\._June 21-5.jpeg
//   - 6.June\Photos\._June 21-6.jpeg
//   - 6.June\Photos\._June 21-7.jpeg
//   - 6.June\Photos\._June 23-1.jpeg
//   - 6.June\Photos\._June 23-2.jpeg
//   - 6.June\Photos\._June 23-3.jpeg
//   - 6.June\Photos\._June 23-4.jpeg
//   - 6.June\Photos\._June 23-5.jpeg
//   - 6.June\Photos\._June 25-1.jpeg
//   - 6.June\Photos\._June 29-1.jpeg
//   - 6.June\Photos\June 14-1.jpeg
//   - 6.June\Photos\June 16-1.JPG
//   - 6.June\Photos\June 21-4.jpeg
//   - 6.June\Photos\June 29-1.jpeg
//   - 7.July\Photos\._July 3-1.jpeg
//   - 7.July\Photos\._July 4-1.jpeg
//   - 7.July\Photos\._July 4-2.jpeg
//   - 7.July\Photos\._July 5-1.jpeg
//   - 7.July\Photos\._july 5-2.jpeg
//   - 7.July\Photos\._July 5-3.jpeg
//   - 7.July\Photos\._July 10-1.jpeg
//   - 7.July\Photos\._July 11-1.jpeg
//   - 7.July\Photos\._July 11-2.jpeg
//   - 7.July\Photos\._July 11-3.jpeg
//   - 7.July\Photos\._July 11-5.jpeg
//   - 7.July\Photos\._July 12-1.jpeg
//   - 7.July\Photos\._July 12-2.jpeg
//   - 7.July\Photos\._July 16-1.jpeg
//   - 7.July\Photos\._July 17-1.jpeg
//   - 7.July\Photos\._July 17-2.jpeg
//   - 7.July\Photos\._July 17-3.jpeg
//   - 7.July\Photos\._July 17-4.jpeg
//   - 7.July\Photos\._July 17-5.jpeg
//   - 7.July\Photos\._July 17-6.jpeg
//   - 7.July\Photos\._July 17-7.jpeg
//   - 7.July\Photos\._July 18-1.jpeg
//   - 7.July\Photos\._July 18-2.jpeg
//   - 7.July\Photos\._July 18-3.jpeg
//   - 7.July\Photos\._July 18-4.jpeg
//   - 7.July\Photos\._July 30-1.jpeg
//   - 7.July\Photos\._July 30-2.jpeg
//   - 7.July\Photos\._July 30-3.jpeg
//   - 7.July\Photos\._July 30-4.jpeg
//   - 7.July\Photos\._July 30-5.jpeg
//   - 7.July\Photos\._July 30-6.jpeg
//   - 7.July\Photos\._July 30-7.jpeg
//   - 7.July\Photos\._July 30-8.jpeg
//   - 7.July\Photos\._July 30-9.jpeg
//   - 7.July\Photos\._July 30-10.jpeg
//   - 7.July\Photos\._July 30-11.jpeg
//   - 7.July\Photos\._July 30-12.jpeg
//   - 7.July\Photos\._July 30-13.jpeg
//   - 7.July\Photos\._July 30-14.jpeg
//   - 7.July\Photos\July 4-1.jpeg
//   - 7.July\Photos\July 4-2.jpeg
//   - 7.July\Photos\July 5-3.jpeg
//   - 7.July\Photos\July 11-3.jpeg
//   - 7.July\Photos\July 17-4.jpeg
//   - 7.July\Photos\July 17-5.jpeg
//   - 7.July\Photos\July 17-6.jpeg
//   - 7.July\Photos\July 17-7.jpeg
//   - 7.July\Photos\July 30-14.jpeg
//   - 8.August\Photos\._Aug 1-1.jpeg
//   - 8.August\Photos\._Aug 1-2.jpeg
//   - 8.August\Photos\._Aug 2-1.jpeg
//   - 8.August\Photos\._Aug 2-2.jpeg
//   - 8.August\Photos\._Aug 6-1.jpeg
//   - 8.August\Photos\._Aug 8-1.jpeg
//   - 8.August\Photos\._Aug 8-2.jpeg
//   - 8.August\Photos\._Aug 8-3.jpeg
//   - 8.August\Photos\._Aug 9-1.jpeg
//   - 8.August\Photos\._Aug 9-2.jpeg
//   - 8.August\Photos\._Aug 10-1.jpeg
//   - 8.August\Photos\._Aug 11-1.jpeg
//   - 8.August\Photos\._Aug 13-1.jpeg
//   - 8.August\Photos\._Aug 14-1.jpeg
//   - 8.August\Photos\._Aug 14-2.jpeg
//   - 8.August\Photos\._Aug 14-3.jpeg
//   - 8.August\Photos\._Aug 14-4.jpeg
//   - 8.August\Photos\._Aug 14-5.jpeg
//   - 8.August\Photos\._Aug 15-1.jpeg
//   - 8.August\Photos\._Aug 15-2.jpeg
//   - 8.August\Photos\._Aug 15-3.jpeg
//   - 8.August\Photos\._Aug 15-4.jpeg
//   - 8.August\Photos\._Aug 15-5.jpeg
//   - 8.August\Photos\._Aug 15-7.jpeg
//   - 8.August\Photos\._Aug 15-8.jpeg
//   - 8.August\Photos\._Aug 15-9.jpeg
//   - 8.August\Photos\._Aug 16-1.jpeg
//   - 8.August\Photos\._Aug 17-1.jpeg
//   - 8.August\Photos\._Aug 18-1.jpeg
//   - 8.August\Photos\._Aug 30-1.jpeg
//   - 8.August\Photos\._Aug 30-2.jpeg
//   - 8.August\Photos\._Aug 30-3.jpeg
//   - 8.August\Photos\._Aug 30-4.jpeg
//   - 8.August\Photos\._Aug 30-5.jpeg
//   - 8.August\Photos\._Aug 31-1.jpeg
//   - 8.August\Photos\._Aug 31-4.jpeg
//   - 8.August\Photos\._Aug 31-5.jpeg
//   - 8.August\Photos\._Aug 31-6.jpeg
//   - 8.August\Photos\._Aug 31-7.jpeg
//   - 8.August\Photos\._Aug 31-8.jpeg
//   - 8.August\Photos\Aug 6-1.jpeg
//   - 8.August\Photos\Aug 8-1.jpeg
//   - 8.August\Photos\Aug 8-3.jpeg
//   - 8.August\Photos\Aug 11-1.jpeg
//   - 8.August\Photos\Aug 13-1.jpeg
//   - 9.September\Photos\._Sept 4-1.jpeg
//   - 9.September\Photos\._Sept 4-2.jpeg
//   - 9.September\Photos\._Sept 6-1.jpeg
//   - 9.September\Photos\._Sept 6-2.jpeg
//   - 9.September\Photos\._Sept 7-1.jpeg
//   - 9.September\Photos\._Sept 8-1.jpeg
//   - 9.September\Photos\._Sept 11-1.jpeg
//   - 9.September\Photos\._sept 15-1.PNG
//   - 9.September\Photos\._Sept 17-1.jpeg
//   - 9.September\Photos\._sept 17-2.jpeg
//   - 9.September\Photos\._sept 19-1.jpeg
//   - 9.September\Photos\Sept 6-1.jpeg
//   - 9.September\Photos\Sept 11-1.jpeg
//   - 9.September\Photos\sept 15-1.PNG
//   - 9.September\Photos\sept 19-1.jpeg
//   - 9.September\Photos\sept 23\._IMG_2077.JPG
//   - 9.September\Photos\sept 23\IMG_2077.JPG

export { photoLocations };
